server:
  port: 8081

spring:
  application:
    name: Application Dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://localhost:3306/profiles
    username: root
    password: 0524