server:
  port: 8082

spring:
  application:
    name: Application Prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://prod:3306/profiles
    username: prod
    password: prod