server:
  port: 8088

spring:
  application:
    name: Application Dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: '0524'
