DROP TABLE IF EXISTS BILLIONAIRES;

CREATE TABLE BILLIONAIRES (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(55) NOT NULL,
    LAST_NAME VARCHAR(55) NOT NULL,
    INDUSTRY VARCHAR(55) DEFAULT NULL
);

INSERT INTO BILLIONAIRES(FIRST_NAME, LAST_NAME, INDUSTRY) VALUES
('BILL', 'GATES', 'TECH'),
('ELON', 'MUSK', 'TECH'),
('JEFF', 'BEZOS', 'COMMERCE');